### ISSUE TITLE
setOnAfterDraw is not a function...

### ISSUE THREAD

**Issue by Martin-Luckow** [VirtuoWorks/CanvasCameraPlugin#6]
Hi there.
The error occurs in my project and in your demo:
As soon as I add an empty function to the options I get this error.
I used your sample, i.e.
...
                onAfterDraw: function (frame) {
                    // do something with each frame 
                }
...

"TypeError: this.canvas.fullsize.setOnAfterDraw is not a function
    at CanvasCamera.setRenderingPresets (file:///android_asset/www/plugins/com.virtuoworks.cordova-plugin-canvascamera/www/CanvasCamera.js:492:34)
    at CanvasCamera.start (file:///android_asset/www/plugins/com.virtuoworks.cordova-plugin-canvascamera/www/CanvasCamera.js:377:10)

**Comment by Martin-Luckow** [comment]
Typo in row 491 in CanvasCamera.js:  this.canvas.fullsize.**setOnAfterDraw**(this.options.onAfterDraw);
Must be --> this.canvas.fullsize.**setAfterDraw**(this.options.onAfterDraw);

**Comment by Sami-Radi** [comment]
Thanks for reporting the issue.
